# P5/2 DMS WCS3 Mockservice Tenant Configuration

# tenant 
TENANT_CAPTION: Prod - WCS3 To REST Adapter

# http port of service
WDSREST_HTTP_PORT: 6950

# rest connector type 
WDSREST_CONNECTOR: '??????'
WDSREST_BASEURL: '?????????????'
WDSREST_BEARER: ''

# extend logging of soap calls
WDSREST_SOAP_LOG: true 
WDSREST_SOAPCONFIG_LOG: true
WDSREST_BUILD_VIEWER_URL: true
