# P5 DMS WCS3 Restservice Tenant Configuration

# tenant 
TENANT_CAPTION: Test - WCS3 To REST Adapter

# http port of service
WDSREST_HTTP_PORT: 6951

# rest connector type 
WDSREST_CONNECTOR: kendox
WDSREST_BASEURL: 'http://<kendoxserver>:<port>'
WDSREST_AUTH_USER: '<kendoxuser>'
WDSREST_AUTH_PASSWORD: 'kendoxpassword>'
#WDSREST_AUTH_ENCRYPTPASSWORD: '<kendoxcliencryptpassword>'

# extend logging of soap calls
WDSREST_SOAP_LOG: true 
WDSREST_SOAPCONFIG_LOG: true
