# P5 DMS WCS3 Restservice Tenant Configuration

# tenant 
TENANT_CAPTION: Test - WCS3 To REST Adapter

# http port of service
WDSREST_HTTP_PORT: 6951

# rest connector type 
WDSREST_CONNECTOR: <connector>
WDSREST_BASEURL: 'https://<server>:<port>'
WDSREST_AUTH_BEARER: <bearertoken>
WDSREST_D3_REPOSITORYID: <repositoryid>

# extend logging of soap calls
WDSREST_SOAP_LOG: true 
WDSREST_SOAPCONFIG_LOG: true
WDSREST_BUILD_VIEWER_URL: true