server:
  swagger:
    enable: WDS_SWAGGERUI_ENABLE
    stats: WDS_SWAGGERSTATS
  authorization:
    systemPassword: WDS_SYSTEMPASSWORD
metric:
  enabled: WDS_METRIC_ENABLE
  tenantid: WDS_TENANTID
retrieval:
  url: RETRIEVAL_URL
context:
  WCS3Rest: 
    application: 
      title: TENANT_CAPTION
    server: 
      http: 
        port: WDSREST_HTTP_PORT 
      soap:
        url: WDSREST_SOAP_URL 
        log: WDSREST_SOAP_LOG 
      soapConfig:
        url: WDSREST_SOAPCONFIG_URL 
        log: WDSREST_SOAPCONFIG_LOG
    viewer:
      buildViewerUrl: WDSREST_BUILD_VIEWER_URL
    propertyStore: 
      path: WDSREST_PROPERTYSTORE_PATH
    config:
      restConnector: WDSREST_CONNECTOR
    env: 
      baseURL: WDSREST_BASEURL
      auth_bearer: WDSREST_AUTH_BEARER
      d3_repositoryId: WDSREST_D3_REPOSITORYID