server:
  swagger:
    enable: WDS_SWAGGERUI_ENABLE
    stats: WDS_SWAGGERSTATS
metric:
  enabled: WDS_METRIC_ENABLE
  tenantid: WDS_TENANTID
context:
  WCS3Rest: 
    application: 
      title: TENANT_CAPTION
    server: 
      http: 
        port: WDSREST_HTTP_PORT 
      soap:
        url: WDSREST_SOAP_URL 
        log: WDSREST_SOAP_LOG 
      soapConfig:
        url: WDSREST_SOAPCONFIG_URL 
        log: WDSREST_SOAPCONFIG_LOG
    propertyStore: 
      path: WDSREST_PROPERTYSTORE_PATH
    config:
      restConnector: WDSREST_CONNECTOR
    env: 
      baseURL: WDSREST_BASEURL
      user: WDSREST_AUTH_USER 
      password: WDSREST_AUTH_PASSWORD 
      encryptPassword: WDSREST_AUTH_ENCRYPTPASSWORD