server:
  log: 
    severity: debug
    # serviceName: GlobalService # if empty uses context name
    transports:
      DailyRotateFile:
        active: true
        options:
          datePattern: YYYY-MM-DD # rotate daily
          dirname: logs # dirname from 
          # filename:     # if empty => uses serviceName
          extension: .log
          maxSize: 20m # max size of file is 20mb
          maxFiles: 14d   #delete files after 14 days
      Console:
        active: true
  swagger:
    enable: true
    file: assets/openapi.yaml
    uipath: /api-docs
    stats: true
  authorization:
    enable: false
    certAuth: false
  bindProtocol: ['http']
metric: 
  enabled: true 
  tenantid: WCS3 REST
services:
  retrieval: 
    url: 'http://localhost:8080'
context:
  WCS3Rest: 
    application: 
      title: WCS3 Contentservice REST
    server: 
      http: 
        port: 8030
      soap:
        url: 'http://127.0.0.1:8030/soap/ContentService'
        log: true
      soapConfig:
        url: 'http://127.0.0.1:8030/soap/ContentConfigurationService'
        log: false
    propertyStore:
      path: ./store.json
    viewer:
      serverURL: null
      forwardURL: null
    config: 
      file: wcs3rest/config.yaml
      restConnector: none
    env: 
      baseURL: ''
      user: ''
      password: ''
      encryptPassword: ''
    metric: 
      subtitle: 'Content Service Rest'
